---
# Main collection of env. vars to set for all tasks and scripts.
env:
  ####
  #### Global variables used for all tasks
  ####
  CONMON_SLUG: "github.com/containers/conmon"

  # Overrides default location (/tmp/cirrus) for repo clone (will become $SRC)
  CIRRUS_WORKING_DIR: "/var/tmp/src/${CONMON_SLUG}"
  # Required so $ENVLIB gets loaded and /bin/sh is not used
  CIRRUS_SHELL: "/bin/bash"
  # Save a little typing (path relative to $CIRRUS_WORKING_DIR)
  SCRIPT_BASE: "./contrib/cirrus"
  # Spoof self as travis, as cirrus has the same test issues as travis does
  TRAVIS: "true"

  # VM Image built in containers/automation_images
  IMAGE_SUFFIX: "c20250721t181111z-f42f41d13"
  FEDORA_CACHE_IMAGE_NAME: "fedora-${IMAGE_SUFFIX}"

  # Container FQIN's
  FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:${IMAGE_SUFFIX}"
  PRIOR_FEDORA_CONTAINER_FQIN: "quay.io/libpod/prior-fedora_podman:${IMAGE_SUFFIX}"

# Only github users with write-access can define or use encrypted variables
# This credential represents a service account with access to manage both VMs
# and storage.
gcp_credentials: ENCRYPTED[13e51806369f650e6ccc326338deeb3c24052fc0a7be29beef2b96da551aed3200abbb6c6406a936bb4388fb2758405c]

# Default VM to use unless set or modified by task
gce_instance:
  image_project: "libpod-218412"
  zone: "us-central1-f" # Required by Cirrus for the time being
  cpu: 2
  memory: "4Gb"
  disk: 200 # Required for performance reasons
  image_name: "${FEDORA_CACHE_IMAGE_NAME}"

# Default timeout for each task
timeout_in: "120m"

# Verify build completes successfully
build_task:
  # Runs within Cirrus's "community cluster"
  gce_instance:
    image_name: "${FEDORA_CACHE_IMAGE_NAME}"
    cpu: 1
    memory: 4
    disk: 200

  script:
    - dnf install -y make glib2-devel git gcc pkg-config systemd-devel libseccomp-devel
    - cd $CIRRUS_WORKING_DIR
    - make

# Verify build completes successfully
unit_task:
  # Runs within Cirrus's "community cluster"
  gce_instance:
    image_name: "${FEDORA_CACHE_IMAGE_NAME}"
    cpu: 1
    memory: 4
    disk: 200

  script:
    - dnf install -y rust make glib2-devel git gcc pkg-config systemd-devel libseccomp-devel
    - cd $CIRRUS_WORKING_DIR
    - make
    - make unit

# Verify build completes successfully
e2e_task:
  # Runs within Cirrus's "community cluster"
  gce_instance:
    image_name: "${FEDORA_CACHE_IMAGE_NAME}"
    cpu: 1
    memory: 4
    disk: 200

  script:
    - dnf install -y rust make glib2-devel git gcc pkg-config systemd-devel libseccomp-devel
    - cd $CIRRUS_WORKING_DIR
    - make
    - make e2e


# This task is critical.  It updates the "last-used by" timestamp stored
# in metadata for all VM images.  This mechanism functions in tandem with
# an out-of-band pruning operation to remove disused VM images.
meta_task:
  name: "VM img. keepalive"
  alias: meta
  container:
    cpu: 2
    memory: 2
    image: quay.io/libpod/imgts:latest
  env:
    # Space-separated list of images used by this repository state
    IMGNAMES: >-
      ${FEDORA_CACHE_IMAGE_NAME}
    BUILDID: "${CIRRUS_BUILD_ID}"
    REPOREF: "${CIRRUS_REPO_NAME}"
    GCPJSON: ENCRYPTED[08de2c74178470b1bc85a107e9962f06dbd11d33c7adf024d3e48ae4399ca5383f9d3ad0e2fd65c3ce12750dd6ef8803]
    GCPNAME: ENCRYPTED[561ce33a9357e5b8e3fb54739c3af31730c0c3b736792f16a67026a8544379d83ff3c27d6fea1c7797a6ae49b6e58115]
    GCPPROJECT: libpod-218412
  clone_script: &noop mkdir -p $CIRRUS_WORKING_DIR
  script: /usr/local/bin/entrypoint.sh
